/**
 * ★ كل النصوص العربية الظاهرة للمستخدم ★
 *
 * لا تكتب نصًا عربيًا داخل المكونات — أضفه هنا واستورده.
 * هذا يحقق متطلب تعديل "النصوص الرئيسية" من مكان مركزي، ويجعل
 * إضافة الإنجليزية لاحقًا نسخ ملف واحد لا مسحًا للمشروع كله.
 */
export const ar = {
  common: {
    search: "بحث",
    searchPlaceholder: "ابحث عن كشتة، مخيم، شاليه، أو خدمة",
    viewDetails: "عرض التفاصيل",
    bookNow: "احجز الآن",
    addToCart: "أضف إلى السلة",
    contactHost: "تواصل مع صاحب المكان",
    addToFavorites: "أضف إلى المفضلة",
    removeFromFavorites: "إزالة من المفضلة",
    showAll: "عرض الكل",
    filters: "الفلاتر",
    clearFilters: "مسح الفلاتر",
    apply: "تطبيق",
    cancel: "إلغاء",
    save: "حفظ",
    edit: "تعديل",
    delete: "حذف",
    back: "رجوع",
    next: "التالي",
    previous: "السابق",
    loading: "جارٍ التحميل…",
    perNight: "لليلة",
    perDay: "لليوم",
    perHour: "للساعة",
    perPerson: "للشخص",
    perUnit: "للقطعة",
    perBooking: "للحجز",
    perKm: "للكيلومتر",
    rating: "التقييم",
    reviews: "تقييم",
    from: "من",
    to: "إلى",
    guests: "عدد الأشخاص",
    city: "المدينة",
    date: "التاريخ",
    listView: "قائمة",
    mapView: "خريطة",
    soon: "قريبًا",
  },

  nav: {
    home: "الرئيسية",
    places: "الأماكن",
    services: "الخدمات",
    cart: "السلة",
    account: "حسابي",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    logout: "تسجيل الخروج",
    becomeHost: "أضف مكانك",
    help: "المساعدة",
  },

  home: {
    heroTitle: "احجز كشتتك، ونجهّزها لك",
    heroSubtitle:
      "أماكن برية ومخيمات وشاليهات في كل مناطق المملكة، وخدمات تجهيز توصلك لموقعك.",
    featured: "أماكن مميزة",
    newest: "أحدث الإضافات",
    topRated: "الأكثر تقييمًا",
    nearby: "كشتات قريبة منك",
    featuredServices: "خدمات مميزة",
    setupServices: "تجهيزات الكشتات",
    categories: "التصنيفات",
    exploreMap: "استكشف على الخريطة",
  },

  search: {
    title: "نتائج البحث",
    resultsCount: "نتيجة",
    noResults: "لا توجد نتائج مطابقة",
    noResultsHint: "جرّب توسيع نطاق البحث أو تقليل الفلاتر.",
    sortBy: "ترتيب حسب",
    sortRecommended: "الأنسب",
    sortPriceAsc: "الأقل سعرًا",
    sortPriceDesc: "الأعلى سعرًا",
    sortRating: "الأعلى تقييمًا",
    sortNewest: "الأحدث",
    priceRange: "نطاق السعر",
    placeType: "نوع المكان",
    serviceType: "نوع الخدمة",
    amenities: "المرافق",
    bookingType: "نوع الحجز",
  },

  listing: {
    about: "عن المكان",
    aboutService: "عن الخدمة",
    amenities: "المرافق",
    location: "الموقع",
    pricing: "الأسعار",
    availability: "الأوقات المتاحة",
    addons: "الخدمات الإضافية",
    policies: "السياسات",
    checkIn: "وقت الدخول",
    checkOut: "وقت الخروج",
    capacity: "السعة",
    reviews: "التقييمات",
    noReviews: "لا توجد تقييمات بعد",
    cancellationPolicy: "سياسة الإلغاء",
    requiresDelivery: "تحتاج توصيل",
    deliveryFee: "رسوم التوصيل",
    freeDelivery: "توصيل مجاني",
  },

  booking: {
    title: "تفاصيل الحجز",
    bookingType: "نوع الحجز",
    hourly: "بالساعة",
    daily: "باليوم",
    nightly: "بالليلة",
    startTime: "وقت البداية",
    endTime: "وقت النهاية",
    contractedWindow: "الفترة المتفق عليها",
    availableAgainAt: "المكان متاح مجددًا من",
    actualCheckIn: "الدخول الفعلي",
    actualCheckOut: "الخروج الفعلي",
    total: "الإجمالي",
    subtotal: "المجموع",
    addonsTotal: "الخدمات الإضافية",
    commission: "عمولة المنصة",
    netEarnings: "صافي الأرباح",
    discount: "الخصم",
    confirm: "تأكيد الحجز",
    statuses: {
      pending: "بانتظار التأكيد",
      confirmed: "مؤكد",
      checked_in: "تم الدخول",
      checked_out: "تم الخروج",
      completed: "مكتمل",
      cancelled: "ملغى",
    },
  },

  order: {
    title: "الطلب",
    items: "الخدمات",
    quantity: "الكمية",
    deliveryLocation: "موقع التوصيل",
    serviceTime: "وقت الخدمة",
    servicesTotal: "قيمة الخدمات",
    extraFees: "رسوم إضافية",
    grandTotal: "الإجمالي النهائي",
    checkout: "إتمام الطلب",
    emptyCart: "سلتك فارغة",
    emptyCartHint: "أضف خدمات لتظهر هنا.",
    statuses: {
      pending: "بانتظار التأكيد",
      confirmed: "مؤكد",
      preparing: "قيد التجهيز",
      out_for_delivery: "خرج للتوصيل",
      delivered: "تم التوصيل",
      completed: "مكتمل",
      cancelled: "ملغى",
    },
  },

  account: {
    title: "حسابي",
    overview: "نظرة عامة",
    profile: "معلومات الحساب",
    upcomingBookings: "الحجوزات القادمة",
    pastBookings: "الحجوزات السابقة",
    orders: "الطلبات",
    favorites: "المفضلة",
    reviews: "تقييماتي",
    notifications: "الإشعارات",
    addresses: "عناويني",
  },

  host: {
    title: "لوحة المزوّد",
    overview: "نظرة عامة",
    places: "أماكني",
    services: "خدماتي",
    addPlace: "إضافة مكان",
    addService: "إضافة خدمة",
    calendar: "التقويم",
    bookings: "الحجوزات",
    orders: "الطلبات",
    addons: "الخدمات الإضافية",
    reviews: "التقييمات",
    earnings: "الأرباح",
    totalBookings: "إجمالي الحجوزات",
    totalOrders: "إجمالي الطلبات",
    totalEarnings: "إجمالي الأرباح",
    views: "المشاهدات",
  },

  admin: {
    title: "لوحة الإدارة",
    overview: "نظرة عامة",
    users: "المستخدمون",
    places: "الأماكن",
    services: "الخدمات",
    bookings: "الحجوزات",
    orders: "الطلبات",
    payments: "المدفوعات",
    reviews: "التقييمات",
    reports: "التقارير",
    settings: "الإعدادات",
    branding: "الهوية والثيم",
    commission: "العمولة",
    pendingReview: "قيد المراجعة",
    approve: "قبول",
    reject: "رفض",
    suspend: "تعليق",
    totalUsers: "عدد المستخدمين",
    totalSales: "إجمالي المبيعات",
    totalCommission: "إجمالي العمولات",
  },

  auth: {
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    fullName: "الاسم الكامل",
    phone: "رقم الجوال",
    forgotPassword: "نسيت كلمة المرور؟",
    resetPassword: "إعادة تعيين كلمة المرور",
    accountType: "نوع الحساب",
    customer: "عميل",
    host: "صاحب مكان / مقدم خدمة",
    haveAccount: "لديك حساب؟",
    noAccount: "ليس لديك حساب؟",
  },

  states: {
    emptyTitle: "لا يوجد شيء هنا بعد",
    errorTitle: "حدث خطأ غير متوقع",
    errorHint: "حاول مرة أخرى، وإن تكرّر الخطأ تواصل معنا.",
    retry: "إعادة المحاولة",
    notFoundTitle: "الصفحة غير موجودة",
    notFoundHint: "الرابط الذي فتحته غير صحيح أو تم حذف المحتوى.",
    backHome: "العودة للرئيسية",
    phasePlaceholder:
      "هذه الشاشة جاهزة هيكليًا وتُربط ببيانات حقيقية في المرحلة القادمة.",
  },

  footer: {
    rights: "جميع الحقوق محفوظة",
    about: "عن المنصة",
    terms: "الشروط والأحكام",
    privacy: "سياسة الخصوصية",
    contact: "تواصل معنا",
  },
} as const;

export type Dictionary = typeof ar;
